# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(default='Open', max_length=10),
        ),
    ]
